name: python 3.7
channels:
  - conda-forge
dependencies:
  - python==3.7.10
  - numpy==1.20.1
  - matplotlib==2.2.2
  - sympy==1.8
  - scipy==1.5.4
  - networkx==2.5.1
  - pip
  - pip:
    - BondGraphTools==0.3.9