#!/bin/bash
pip install --upgrade --no-deps --force-reinstall numpy==1.20.3 julia==0.5.6 diffeqpy==1.2.0
python diffeq_setup.py

# Commands to make Python call Julia successfully in Binder
cd /srv/conda/envs/notebook/share/jupyter/kernels
cd python3
cp ~/kernel.json ./
